### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by gzhhong** [brankas/emoji#1]
Hello, 

I run the command
```
 go get -u github.com/kenshaw/emoji
```
The import github.com/kenshaw/emoji in my source code. When I run the code there is error:

found packages emoji (emoji.go) and main (gen.go) in $GOPATH/pkg/mod/github.com/kenshaw/emoji@v0.2.1. 

I have to remove the $GOPATH/pkg/mod/github.com/kenshaw/emoji@v0.2.1/gen.go, then my application can run.

Any suggestions?

Thanks,

james

**Comment by nbossard** [comment]
Hello James, 
If you look at beginning of file: 
[gen.go](https://github.com/kenshaw/emoji/blob/v0.2.1/gen.go)

You will see the first line is 

```go
//go:build ignore
```

This means this file should be ignored at compilation, cf : 
<https://pkg.go.dev/cmd/go#hdr-Build_constraints>

You are using an old version of go that does not support this syntax, please upgrade to at least 1.16

**Comment by gzhhong** [comment]
@nbossard , Bonjour Professor Nico, merci beaucoup. :smile_face:

**Comment by kenshaw** [comment]
@gzhhong please upgrade to latest Go version.
